### PR TITLE
Add limitation on parallel threads

### PR DESCRIPTION
**Pull request by high-stakes**

### CODE REVIEW

**Comment by high-stakes** [comment]
Hey, sorry was quite busy but added thread limiting

**Comment by anshumanbh** [comment]
why did you close this @high-stakes ?

**Comment by high-stakes** [comment]
Edit: Realized, we probably should not add all jobs into the same queue because we can porentially end up with a deadlock so ideally only jobs which are "leaves" should be run async. Because if the queue only contains "parent" jobs no "leaves" can execute and not parent can finish.

For example, there is really no point in adding "scanforeachuser" as an async execution then also adding "runGitTools" also as async.
So my vote is to only run "leaf" jobs as async or we need to have separate queues on a job-type basis.

**Comment by anshumanbh** [comment]
So, if I am understanding you correctly, you are suggesting we keep the threading the way it is right now?

**Comment by high-stakes** [comment]
No, my suggestion is to use thread limit for "leaf" jobs only ("gitclone" and "rungittools") and either remove go-routines from the rest of the methods or just keep them like they are. I think the other methods don't really need to be async though as they do not do the heavy lifting, only the above mentioned 2.

**Comment by anshumanbh** [comment]
Ah okay. Do you want to take a stab at modifying the code accordingly?

**Comment by high-stakes** [comment]
Yes, going to do it.

**Comment by high-stakes** [comment]
Change added

**Comment by anshumanbh** [comment]
@high-stakes Just did a dry run on an org with a lot of repos and users. It cloned all the repos just fine. But, then I got this message:

```
panic: signal: killed

goroutine 1260 [running]:
main.check(0x7fe5e0, 0xc4201bc660)
        /data/main.go:57 +0x174
main.runTrufflehog(0xc4201a05c0, 0x18, 0xc4201d5ad0, 0x8, 0x7ffca2794ddb, 0x4, 0x0, 0x0)
        /data/main.go:277 +0x244
main.runGitTools(0x6dd63f, 0x3, 0xc4201a05c0, 0x18, 0xc4201f63c0, 0xc4201d5ad0, 0x8, 0x7ffca2794ddb, 0x4)
        /data/main.go:296 +0x203
main.scanDir.func1.1()
        /data/main.go:442 +0x199
main.enqueueJob.func1(0xc4201c0140)
        /data/main.go:45 +0x27
created by main.enqueueJob
        /data/main.go:47 +0x6a
```

**Comment by anshumanbh** [comment]
Maybe, we need to add the func for `go scanforeachuser` as well?

**Comment by anshumanbh** [comment]
I also tried just scanning org repositories and I ended up getting a similar error:

```
panic: signal: killed

goroutine 388 [running]:
main.check(0x7fe5e0, 0xc42018e060)
        /data/main.go:57 +0x174
main.runTrufflehog(0xc4201c6800, 0x18, 0xc4201b56d0, 0x8, 0x7ffe359d0dd2, 0x4, 0x0, 0x0)
        /data/main.go:277 +0x244
main.runGitTools(0x6dd63f, 0x3, 0xc4201c6800, 0x18, 0xc4201d6680, 0xc4201b56d0, 0x8, 0x7ffe359d0dd2, 0x4)
        /data/main.go:296 +0x203
main.scanDir.func1.1()
        /data/main.go:442 +0x199
main.enqueueJob.func1(0xc42022c400)
        /data/main.go:45 +0x27
created by main.enqueueJob
        /data/main.go:47 +0x6a
```

I am guessing this is because truffleHog is taking too long to scan and a kill signal is being sent or something?

**Comment by high-stakes** [comment]
Can you send the org you are running against? I probably am not using orgs big enough. this might be an out of memory problem as too many goroutines a created and not destroyed because they need to wait for the queue to finish. So we probably should not be creating those goroutines in the first place, they serve no real benefit anyway.

**Comment by anshumanbh** [comment]
Its an internal repo you cant get to. And, I am thinking the same..to get rid of the go routines all together. They are just not worth it specially for large orgs

**Comment by high-stakes** [comment]
I am going to do one final change and maybe you can try that later: remove goroutines for everything except for the job queue -> this should not cause memory overload as the threads will just block and no new is created until the queue can progress

**Comment by anshumanbh** [comment]
Sounds good!

**Comment by anshumanbh** [comment]
Closing this for now as the changes in this PR were already merged manually. I think the issue is that some repos might be so big for trufflehog that it fails to scan it and sends a kill signal. I have modified the code to not barf at that point and continue scanning. It will however print what repo failed so that the user can go and manually scan it.

**Comment by high-stakes** [comment]
I added the change we discussed earlier, still want me to push it? Probably prevents those edge cases

**Comment by anshumanbh** [comment]
@high-stakes I've been running it on multiple repos and so far it has only failed once. I also implemented a way that if truffleHog fails to scan, it keeps going on instead of quitting. I think we shouldn't compromise on the threading specially because truffleHog fails to scan a repo

**Pull request closed without merging**
